db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/fruitshop_db
db.username=root
db.password=

# Cloudinary
cloudinary.cloud_name=dgszq5oci
cloudinary.api_key=582857512623424
cloudinary.api_secret=Gir-0z42V0AUIzAfm7ohXvM6F4c

#db.driver=com.mysql.cj.jdbc.Driver
#db.url=jdbc:mysql://103.56.160.214:3306/fruitshop_db
#db.username=root
#db.password=12345